# Generated by Django 3.2.13 on 2022-06-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chairman'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='block_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chairman',
            name='house_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
