# Generated by Django 3.2.13 on 2022-06-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220624_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='pic',
            field=models.FileField(default='Media/default_chairman.png', upload_to='Media/images/'),
        ),
    ]
