# Generated by Django 3.2.13 on 2022-07-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_chairman_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='about_me',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
