# Generated by Django 3.2.13 on 2022-07-05 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_chairman_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=85)),
                ('notice_content', models.TextField(max_length=85)),
                ('img', models.ImageField(upload_to='images/Notice')),
                ('video', models.FileField(upload_to='images/Notice/videos')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.chairman')),
            ],
        ),
    ]
